apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        volumeMounts:
        - name: pv1-storage
          mountPath: /data
      volumes:
      - name: pv1-storage
        persistentVolumeClaim:
          claimName: pvc1

