apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.local
    http:
      paths:

      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: deploy-service
            port:
              number: 80

      - path: /app2
        pathType: Prefix
        backend:
          service:
            name: game-app-service
            port:
              number: 80