# varibale in same playbook
---
- hosts: web
  become: yes
  vars:
    type: httpd
    version: latest
  tasks:
    - name: Ensure httpd is installed and running
      yum:
        name: "{{ type }}"
        state: present
    - name: started httpd
      service:
        name: "{{ type }}"
        state: started
        enabled: yes
    - name: print software details
      debug:
        msg: 
          - "we have installed {{ type }} and version is {{ version }}"
          - " now the user is {{ ansible_user }}"
          - "variables is {{ location }}"
