- name: install httpd
  become: yes
  hosts: server-2
  tasks:
    - name: installing httpd
      package:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: display details
      debug:
        - location: "{{ location }}"
        - user: "{{ user }}"