---
- hosts: web
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
      tags: httpd
    - name: install nginx
      yum:
        name: nginx
        state: present
      tags: nginx
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: display httpd details
      debug:
        msg: "we are executing {{ ansible_run_tags }} "
          