---
- hosts: web
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present # uninstall nginx
    - name: display httpd details
      debug:
        msg: 
          - "we have installed {{ myname }} and version is {{ version }}"
          - " now the user is {{ user }}"