---
- hosts: backend
  become: yes
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: present
      tags: nginx
    - name: install httpd
      yum:
        name: httpd
        state: present
      tags: httpd
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: display httpd details
      debug:
        var: ansible_run_tags
      tags: always # this task will always execute irrespective of tags provided in command line
          