- name: install nginx
  become: yes
  hosts: web
  tasks:
    - name: installing nginx
      package:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes  
    - name: execute linux command
      command: hostname -f
      register: result
    - name: display nginx details
      debug:
        msg: 
          - "variables is {{ location }}"
          - "{{ a }}"
          - "{{ b }}"
          - "{{ c }}"
          - "command output is {{ result.stdout }}"