pipeline {
  agent any
    stages {
        stage('build') {
            steps {
                echo 'building'
                sh 'date'
            }
        }
        stage('test') {
            steps {
                echo 'testing..'
            }
        }
        stage('deploy') {
            steps {
                echo "deploying.."
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
    }
}