pipeline {
  agent {
    docker {
        image 'node:16-alpine'
    }
  }
    stages {
        stage('build') {
            steps {
                echo 'building'
                sh 'date'
            }
        }
        stage('test') {
            steps {
                echo 'testing..'
            }
        }
        stage('deploy') {
            steps {
                echo "deploying.."
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'Hi your task was successfully executed'
        }
        failure {
            echo 'This will run only if failed'
        }
    }
}